/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import datos.BDAcceso;
import datos.BDConsulta;
import datos.BDDoctor;
import datos.BDPaciente;
import datos.Conexion;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Acceso;
import negocio.Consulta;
import negocio.Doctor;
import negocio.Paciente;

/**
 *
 * @author Administrador
 */
public class Inicio extends javax.swing.JFrame {
    String [][] matriz= new String[100][5];
    String [][] matrizDoctor = new String[100][7];
    DefaultTableModel modelo;
    ArrayList<Doctor> lista;
    /**
     * Creates new form Inicio
     */
    public Inicio() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Consultorio Medico");
        setIconImage(new ImageIcon(getClass().getResource("/iconos/iconbeu.png")).getImage());
        jplogin.setVisible(true);
        jtPanel.setVisible(false);
        lblMensaje.setVisible(false);
        cargarCodigo();
        cargarDoctores();
    }
    
    
    private void cargarDoctores() {
        for (Doctor doctor:lista) {
            cboDoctor.addItem(doctor.getRut());
        }
    }
    
    private void cargarCodigo() throws Exception {
        BDDoctor bdoctor = new BDDoctor();
        lista = bdoctor.listarDoctor();
        DefaultListModel modeloLista = new DefaultListModel();
        for (Doctor doc:lista) {
            modeloLista.addElement(doc.getRut());
        }
    }
    
    /**
     *
     */
 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jtPanel = new javax.swing.JTabbedPane();
        jpbienvenida = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jpBuscarConsulta = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscarConsulta = new javax.swing.JTextField();
        btnBuscarConsulta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaConsulta = new javax.swing.JTextArea();
        btnLimpiarTxta = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jpConsulta = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtConsultaPaciente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cboDoctor = new javax.swing.JComboBox<>();
        jdateConsulta = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPrecioConsulta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtConsultaEspecialidad = new javax.swing.JTextField();
        btnGuardarConsulta = new javax.swing.JButton();
        txtConsultaNombreP = new javax.swing.JLabel();
        txtnPacienteConsulta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtaPacienteConsulta = new javax.swing.JTextField();
        btnBuscarPacienteConsulta = new javax.swing.JButton();
        btnListarConsulta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnEliminarConsulta = new javax.swing.JButton();
        btnLimpiarConsulta = new javax.swing.JButton();
        jpPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRutPaciente = new javax.swing.JTextField();
        txtNombrePaciente = new javax.swing.JTextField();
        txtApPaciente = new javax.swing.JTextField();
        txtCorreoPaciente = new javax.swing.JTextField();
        jdatePaciente = new com.toedter.calendar.JDateChooser();
        btnGuardarPaciente = new javax.swing.JButton();
        btnBuscarPaciente = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();
        btnListarPaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaciente = new javax.swing.JTable();
        btnLimpiarTablaPac = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnLimpiarPaciente = new javax.swing.JButton();
        jpDoctor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnInsertarDoctor = new javax.swing.JButton();
        btnBuscarDoctor = new javax.swing.JButton();
        btnEliminarDoctor = new javax.swing.JButton();
        btnListarDoctor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        txtRutDoctor = new javax.swing.JTextField();
        txtApDoctor = new javax.swing.JTextField();
        txtNombreDoctor = new javax.swing.JTextField();
        txtCorreoDoctor = new javax.swing.JTextField();
        jdateDoctor = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecioDoctor = new javax.swing.JTextField();
        btnLimpiartabla = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        btnLimpiarDoctor = new javax.swing.JButton();
        jplogin = new javax.swing.JInternalFrame();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel33.setText("BIENVENIDO USUARIO");

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setText("En esta interfaz puedes:");

        jLabel35.setText("Buscar consultas");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_medicine_6673737.png"))); // NOI18N

        jLabel37.setText("Agregar o eliminar pacientes");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_matureman2_628283 (1).png"))); // NOI18N

        jLabel39.setText("Agregar o eliminar doctores");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_doctor-asian-male-coronavirus_6040299.png"))); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_stethoscope-doctor-health-medical-healthcare_5859229.png"))); // NOI18N

        jLabel42.setText("Crear y eliminar consultas");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_5_avatar_2754581 (1).png"))); // NOI18N

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel44.setText("¡Puedes hacerlo en las pestañas de arriba!");

        javax.swing.GroupLayout jpbienvenidaLayout = new javax.swing.GroupLayout(jpbienvenida);
        jpbienvenida.setLayout(jpbienvenidaLayout);
        jpbienvenidaLayout.setHorizontalGroup(
            jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbienvenidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addGap(161, 161, 161))
            .addGroup(jpbienvenidaLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel44))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jpbienvenidaLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel45)
                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel40))
                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                        .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpbienvenidaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel36))
                                    .addComponent(jLabel35))
                                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addComponent(jLabel38)
                                        .addGap(48, 48, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbienvenidaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel37))))
                            .addGroup(jpbienvenidaLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel42)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpbienvenidaLayout.createSequentialGroup()
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel43)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel33))
                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel34)))
                .addGap(0, 177, Short.MAX_VALUE))
        );
        jpbienvenidaLayout.setVerticalGroup(
            jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbienvenidaLayout.createSequentialGroup()
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel33))
                    .addGroup(jpbienvenidaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel43)))
                .addGap(32, 32, 32)
                .addComponent(jLabel34)
                .addGap(47, 47, 47)
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46)
                .addGap(71, 71, 71)
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpbienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(46, 46, 46)
                .addComponent(jLabel44)
                .addGap(100, 100, 100))
        );

        jtPanel.addTab("Bienvenido", jpbienvenida);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel23.setText("BUSCAR CONSULTA");

        jLabel24.setText("RUT Paciente:");

        txtBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarConsultaActionPerformed(evt);
            }
        });

        btnBuscarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_magnifying-glass-search-zoom-find_3643762.png"))); // NOI18N
        btnBuscarConsulta.setText("Buscar");
        btnBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConsultaActionPerformed(evt);
            }
        });

        txaConsulta.setColumns(20);
        txaConsulta.setRows(5);
        jScrollPane4.setViewportView(txaConsulta);

        btnLimpiarTxta.setText("Limpiar");
        btnLimpiarTxta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTxtaActionPerformed(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_medicine_6673737.png"))); // NOI18N

        javax.swing.GroupLayout jpBuscarConsultaLayout = new javax.swing.GroupLayout(jpBuscarConsulta);
        jpBuscarConsulta.setLayout(jpBuscarConsultaLayout);
        jpBuscarConsultaLayout.setHorizontalGroup(
            jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarConsultaLayout.createSequentialGroup()
                .addGap(0, 83, Short.MAX_VALUE)
                .addGroup(jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBuscarConsultaLayout.createSequentialGroup()
                        .addGroup(jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel28))
                        .addGap(43, 43, 43)
                        .addGroup(jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jpBuscarConsultaLayout.createSequentialGroup()
                                .addComponent(txtBuscarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarConsulta)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarConsultaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
            .addGroup(jpBuscarConsultaLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnLimpiarTxta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBuscarConsultaLayout.setVerticalGroup(
            jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarConsultaLayout.createSequentialGroup()
                .addGroup(jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBuscarConsultaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel23))
                    .addGroup(jpBuscarConsultaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel28)))
                .addGap(49, 49, 49)
                .addGroup(jpBuscarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(btnBuscarConsulta))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnLimpiarTxta)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jtPanel.addTab("Buscador de consulta", jpBuscarConsulta);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Consulta");

        jLabel14.setText("RUT Paciente:");

        cboDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar" }));
        cboDoctor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDoctorItemStateChanged(evt);
            }
        });
        cboDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDoctorMouseClicked(evt);
            }
        });
        cboDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDoctorActionPerformed(evt);
            }
        });

        jLabel20.setText("Fecha:");

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDCONSULTA", "FECHA", "RUT PACIENTE", "RUT DOCTOR", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblConsulta);

        jLabel18.setText("Rut Doctor:");

        jLabel21.setText("Precio:");

        txtPrecioConsulta.setEditable(false);

        jLabel19.setText("Especialidad:");

        txtConsultaEspecialidad.setEditable(false);

        btnGuardarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_ic_check_circle_48px_3669380.png"))); // NOI18N
        btnGuardarConsulta.setText("Insertar");
        btnGuardarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConsultaActionPerformed(evt);
            }
        });

        txtConsultaNombreP.setText("Nombre Paciente:");

        txtnPacienteConsulta.setEditable(false);

        jLabel22.setText("Apellido Paciente:");

        txtaPacienteConsulta.setEditable(false);

        btnBuscarPacienteConsulta.setText("Buscar");
        btnBuscarPacienteConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteConsultaActionPerformed(evt);
            }
        });

        btnListarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_list-mark-sign-option-menu_3643763.png"))); // NOI18N
        btnListarConsulta.setText("Listar");
        btnListarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarConsultaActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_stethoscope-doctor-health-medical-healthcare_5859229.png"))); // NOI18N

        btnEliminarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_close_309090.png"))); // NOI18N
        btnEliminarConsulta.setText("Eliminar");
        btnEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConsultaActionPerformed(evt);
            }
        });

        btnLimpiarConsulta.setText("Limpiar campos");
        btnLimpiarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaLayout = new javax.swing.GroupLayout(jpConsulta);
        jpConsulta.setLayout(jpConsultaLayout);
        jpConsultaLayout.setHorizontalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtConsultaNombreP)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpConsultaLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtPrecioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaLayout.createSequentialGroup()
                                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(txtnPacienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaLayout.createSequentialGroup()
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpConsultaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConsultaEspecialidad))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(txtaPacienteConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                        .addGap(55, 55, 55))
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListarConsulta)
                            .addComponent(jdateConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel13))
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel14)
                        .addGap(43, 43, 43)
                        .addComponent(txtConsultaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPacienteConsulta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnGuardarConsulta)
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminarConsulta))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimpiarConsulta)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(203, 203, 203))
        );
        jpConsultaLayout.setVerticalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13))
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel25)))
                .addGap(33, 33, 33)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsultaNombreP))
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsultaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(btnBuscarPacienteConsulta))
                        .addGap(22, 22, 22)
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnPacienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtaPacienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdateConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtConsultaEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtPrecioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarConsulta)
                    .addComponent(btnGuardarConsulta)
                    .addComponent(btnEliminarConsulta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarConsulta)
                    .addComponent(jButton1))
                .addGap(32, 32, 32))
        );

        jtPanel.addTab("Mantededor Consulta", jpConsulta);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Paciente");

        jLabel2.setText("RUT:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Fecha de Nacimiento");

        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });

        btnGuardarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_ic_check_circle_48px_3669380.png"))); // NOI18N
        btnGuardarPaciente.setText("Guardar");
        btnGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPacienteActionPerformed(evt);
            }
        });

        btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_magnifying-glass-search-zoom-find_3643762.png"))); // NOI18N
        btnBuscarPaciente.setText("Buscar");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        btnEliminarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_close_309090.png"))); // NOI18N
        btnEliminarPaciente.setText("Eliminar");
        btnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacienteActionPerformed(evt);
            }
        });

        btnListarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_list-mark-sign-option-menu_3643763.png"))); // NOI18N
        btnListarPaciente.setText("Listar");
        btnListarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPacienteActionPerformed(evt);
            }
        });

        tblPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "FECHA NAC", "CORREO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaciente);

        btnLimpiarTablaPac.setText("Limpiar tabla");
        btnLimpiarTablaPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTablaPacActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_matureman2_628283 (1).png"))); // NOI18N

        btnLimpiarPaciente.setText("Limpiar campos");
        btnLimpiarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPacienteLayout = new javax.swing.GroupLayout(jpPaciente);
        jpPaciente.setLayout(jpPacienteLayout);
        jpPacienteLayout.setHorizontalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPacienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPacienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jdatePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(jpPacienteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpPacienteLayout.createSequentialGroup()
                                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPacienteLayout.createSequentialGroup()
                                        .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtRutPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45)
                                        .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(39, 39, 39)
                                        .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpPacienteLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel1))))
                            .addGroup(jpPacienteLayout.createSequentialGroup()
                                .addComponent(btnGuardarPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarPaciente)
                                .addGap(29, 29, 29)
                                .addComponent(btnListarPaciente)
                                .addGap(15, 15, 15)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpPacienteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarPaciente)
                .addGap(59, 59, 59)
                .addComponent(btnLimpiarTablaPac)
                .addGap(216, 216, 216))
        );
        jpPacienteLayout.setVerticalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPacienteLayout.createSequentialGroup()
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPacienteLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jpPacienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRutPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdatePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPaciente)
                    .addComponent(btnBuscarPaciente)
                    .addComponent(btnEliminarPaciente)
                    .addComponent(btnListarPaciente))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarTablaPac)
                    .addComponent(btnLimpiarPaciente))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jtPanel.addTab("Mantenedor Paciente", jpPaciente);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Doctor");

        jLabel8.setText("RUT:");

        jLabel9.setText("Apellido:");

        jLabel10.setText("Fecha nacimiento");

        jLabel11.setText("Nombre:");

        jLabel12.setText("Correo:");

        btnInsertarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_ic_check_circle_48px_3669380.png"))); // NOI18N
        btnInsertarDoctor.setText("Guardar");
        btnInsertarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDoctorActionPerformed(evt);
            }
        });

        btnBuscarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_magnifying-glass-search-zoom-find_3643762.png"))); // NOI18N
        btnBuscarDoctor.setText("Buscar");
        btnBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDoctorActionPerformed(evt);
            }
        });

        btnEliminarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_close_309090.png"))); // NOI18N
        btnEliminarDoctor.setText("Eliminar");
        btnEliminarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDoctorActionPerformed(evt);
            }
        });

        btnListarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_list-mark-sign-option-menu_3643763.png"))); // NOI18N
        btnListarDoctor.setText("Listar");
        btnListarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDoctorActionPerformed(evt);
            }
        });

        tblDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "FECHA NAC", "ESPECIALIDAD", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDoctor);

        txtApDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApDoctorActionPerformed(evt);
            }
        });

        txtCorreoDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoDoctorActionPerformed(evt);
            }
        });

        jLabel15.setText("Especialidad:");

        jLabel16.setText("Precio:");

        btnLimpiartabla.setText("Limpiar tabla");
        btnLimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiartablaActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_doctor-asian-male-coronavirus_6040299.png"))); // NOI18N

        btnLimpiarDoctor.setText("Limpiar campos");
        btnLimpiarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDoctorLayout = new javax.swing.GroupLayout(jpDoctor);
        jpDoctor.setLayout(jpDoctorLayout);
        jpDoctorLayout.setHorizontalGroup(
            jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDoctorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDoctorLayout.createSequentialGroup()
                        .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDoctorLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpDoctorLayout.createSequentialGroup()
                                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRutDoctor)
                                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(txtApDoctor))
                                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDoctorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18))
                                    .addGroup(jpDoctorLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCorreoDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtNombreDoctor)
                                    .addComponent(txtPrecioDoctor))
                                .addGap(55, 55, 55))))
                    .addGroup(jpDoctorLayout.createSequentialGroup()
                        .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpDoctorLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addGap(64, 64, 64)
                                .addComponent(jdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDoctorLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnInsertarDoctor)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarDoctor)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarDoctor)
                                .addGap(18, 18, 18)
                                .addComponent(btnListarDoctor)))
                        .addGap(0, 54, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDoctorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarDoctor)
                .addGap(56, 56, 56)
                .addComponent(btnLimpiartabla)
                .addGap(218, 218, 218))
        );
        jpDoctorLayout.setVerticalGroup(
            jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDoctorLayout.createSequentialGroup()
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDoctorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel27))
                    .addGroup(jpDoctorLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)))
                .addGap(49, 49, 49)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtRutDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(txtApDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtPrecioDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarDoctor)
                    .addComponent(btnBuscarDoctor)
                    .addComponent(btnEliminarDoctor)
                    .addComponent(btnListarDoctor))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiartabla)
                    .addComponent(btnLimpiarDoctor))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jtPanel.addTab("Mantenedor Doctor", jpDoctor);

        jplogin.setVisible(true);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconfinder_revisi_02_2191544.png"))); // NOI18N

        jLabel30.setText("Usuario");

        jLabel31.setText("Clave");

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setText("jLabel32");

        javax.swing.GroupLayout jploginLayout = new javax.swing.GroupLayout(jplogin.getContentPane());
        jplogin.getContentPane().setLayout(jploginLayout);
        jploginLayout.setHorizontalGroup(
            jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jploginLayout.createSequentialGroup()
                .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jploginLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(30, 30, 30)
                        .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtClave, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                    .addGroup(jploginLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnAcceder))
                    .addGroup(jploginLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblMensaje)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jploginLayout.setVerticalGroup(
            jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jploginLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jploginLayout.createSequentialGroup()
                        .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(23, 23, 23)
                        .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addComponent(btnAcceder)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtPanel)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(jplogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtPanel)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(jplogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacienteMouseClicked
        // TODO add your handling code here:
        int fila = tblPaciente.getSelectedRow();
        txtRutPaciente.setText(tblPaciente.getValueAt(fila,0).toString());
        txtNombrePaciente.setText(tblPaciente.getValueAt(fila,1).toString());
        txtApPaciente.setText(tblPaciente.getValueAt(fila,2).toString());
        jdatePaciente.setDateFormatString((String) tblPaciente.getValueAt(fila, 3));
        txtCorreoPaciente.setText(tblPaciente.getValueAt(fila,4).toString());
        // Falta la fecha
    }//GEN-LAST:event_tblPacienteMouseClicked

    private void btnListarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPacienteActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            BDPaciente paciente = new BDPaciente();
            String [] titulos = {"RUT", "NOMBRE", "APELLIDO", "FECHA NAC", "CORREO"};
            ArrayList<Paciente> lista = paciente.listarPaciente();
            for(Paciente paci:lista) {
                matriz[fila][0] = paci.getRut();
                matriz[fila][1] = paci.getNombre();
                matriz[fila][2] = paci.getApellido();
                matriz[fila][3] = String.valueOf(paci.getFechaNacimiento());
                matriz[fila][4] = paci.getCorreo();
                fila++;
            }
            modelo = new DefaultTableModel(matriz,titulos);
            tblPaciente.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnListarPacienteActionPerformed

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
        // TODO add your handling code here:
        try {
            BDPaciente bdpaciente = new BDPaciente();
            if (bdpaciente.eliminarPaciente(txtRutPaciente.getText()) != 0) {
                JOptionPane.showMessageDialog(null, "Paciente Eliminado");
                limpiarControles();
                txtRutPaciente.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró paciente para eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        try {
            BDPaciente bdpaciente = new BDPaciente();
            Paciente paci = bdpaciente.buscarPaciente(txtRutPaciente.getText());
            if (paci.getRut() != null) {
                txtNombrePaciente.setText(paci.getNombre());
                txtApPaciente.setText(paci.getApellido());
                txtCorreoPaciente.setText(paci.getCorreo());
                jdatePaciente.setDate(paci.getFechaNacimiento());
            } else {
                JOptionPane.showMessageDialog(null, "Paciente no encontrado");
                limpiarControles();
                txtRutPaciente.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnGuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPacienteActionPerformed
        try {
            Date date = jdatePaciente.getDate();
            Paciente paciente = new Paciente();
            paciente.setRut(txtRutPaciente.getText());
            paciente.setNombre(txtNombrePaciente.getText());
            paciente.setApellido(txtApPaciente.getText());
            paciente.setFechaNacimiento(date);
            paciente.setCorreo(txtCorreoPaciente.getText());
            BDPaciente bdpaciente = new BDPaciente();
            bdpaciente.insertarPaciente(paciente);
            JOptionPane.showMessageDialog(null,"Paciente Ingresado");
            limpiarControles();
            txtRutPaciente.requestFocus();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarPacienteActionPerformed

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed

    }//GEN-LAST:event_txtNombrePacienteActionPerformed

    private void txtCorreoDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoDoctorActionPerformed

    private void txtApDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApDoctorActionPerformed

    private void tblDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorMouseClicked
        // TODO add your handling code here:
        int fila = tblDoctor.getSelectedRow();
        txtRutDoctor.setText(tblDoctor.getValueAt(fila,0).toString());
        txtNombreDoctor.setText(tblDoctor.getValueAt(fila,1).toString());
        txtApDoctor.setText(tblDoctor.getValueAt(fila,2).toString());
        jdateDoctor.setDateFormatString(tblDoctor.getValueAt(fila, 3).toString());
        txtCorreoDoctor.setText(tblDoctor.getValueAt(fila,4).toString());
        txtEspecialidad.setText(tblDoctor.getValueAt(fila,5).toString());
        txtPrecioDoctor.setText(tblDoctor.getValueAt(fila,6).toString());
    }//GEN-LAST:event_tblDoctorMouseClicked

    private void btnListarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDoctorActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            BDDoctor doctor = new BDDoctor();
            String [] titulos = {"RUT", "NOMBRE", "APELLIDO", "FECHA NAC", "CORREO", "ESPECIALIDAD", "PRECIO"};
            ArrayList<Doctor> lista = doctor.listarDoctor();
            for(Doctor doc:lista) {
                matrizDoctor[fila][0] = doc.getRut();
                matrizDoctor[fila][1] = doc.getNombre();
                matrizDoctor[fila][2] = doc.getApellido();
                matrizDoctor[fila][3] = String.valueOf(doc.getFechaNacimiento());
                matrizDoctor[fila][4] = doc.getCorreo();
                matrizDoctor[fila][5] = doc.getEspecialidad();
                matrizDoctor[fila][6] = String.valueOf(doc.getPrecio());
                fila++;
            }
            modelo = new DefaultTableModel(matrizDoctor,titulos);
            tblDoctor.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnListarDoctorActionPerformed

    private void btnEliminarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDoctorActionPerformed
        // TODO add your handling code here:
        try {
            BDDoctor bddoctor = new BDDoctor();
            if (bddoctor.eliminarDoctor(txtRutDoctor.getText()) != 0) {
                JOptionPane.showMessageDialog(null, "Doctor Eliminado");
                limpiarControles();
                txtRutDoctor.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró doctor para eliminar");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarDoctorActionPerformed

    private void btnBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDoctorActionPerformed
        // TODO add your handling code here:
        try {
            BDDoctor bddoctor = new BDDoctor();
            Doctor doctor = bddoctor.buscarDoctor(txtRutDoctor.getText());
            if (doctor.getRut() != null) {
                txtRutDoctor.setText(doctor.getRut());
                txtNombreDoctor.setText(doctor.getNombre());
                txtApDoctor.setText(doctor.getApellido());
                jdateDoctor.setDate(doctor.getFechaNacimiento());
                txtEspecialidad.setText(doctor.getEspecialidad());
                txtPrecioDoctor.setText(String.valueOf(doctor.getPrecio()));
                txtCorreoDoctor.setText(doctor.getCorreo());

            } else {
                JOptionPane.showMessageDialog(null, "Doctor no encontrado");
                limpiarControles();
                txtRutDoctor.requestFocus();

            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarDoctorActionPerformed

    private void btnInsertarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDoctorActionPerformed
        // TODO add your handling code here:
        try {
            Date datedoc = jdateDoctor.getDate();
            Doctor doctor = new Doctor();
            doctor.setRut(txtRutDoctor.getText());
            doctor.setNombre(txtNombreDoctor.getText());
            doctor.setApellido(txtApDoctor.getText());
            doctor.setFechaNacimiento(datedoc);
            doctor.setCorreo(txtCorreoDoctor.getText());
            doctor.setEspecialidad(txtEspecialidad.getText());
            doctor.setPrecio(Integer.valueOf(txtPrecioDoctor.getText()));
            BDDoctor bddoc = new BDDoctor();
            bddoc.insertarDoctor(doctor);
            JOptionPane.showMessageDialog(null, "Doctor insertado con exito");
            limpiarControles();
            cargarCodigo();
            cargarDoctores();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnInsertarDoctorActionPerformed

    private void btnGuardarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConsultaActionPerformed
        // TODO add your handling code here:
        try {
            Date date = jdateConsulta.getDate();
            Consulta consulta = new Consulta();
            consulta.setIdConsulta(0);
            consulta.setRutPaciente(txtConsultaPaciente.getText());
            consulta.setRutDoctor(cboDoctor.getSelectedItem().toString());
            consulta.setPrecioDoctor(Integer.valueOf(txtPrecioConsulta.getText()));
            consulta.setFechaConsulta(date);
            BDConsulta consul = new BDConsulta();
            consul.insertarConsulta(consulta);
            JOptionPane.showMessageDialog(null,"Consulta Médica ingresada con exito");
            limpiarControles();
            txtRutPaciente.requestFocus();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarConsultaActionPerformed

    private void cboDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDoctorActionPerformed

    private void cboDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDoctorMouseClicked

    }//GEN-LAST:event_cboDoctorMouseClicked

    private void cboDoctorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDoctorItemStateChanged
        // TODO add your handling code here:
        try {
            BDDoctor bddoctor = new BDDoctor();
            Doctor doctor = bddoctor.buscarDoctor(cboDoctor.getSelectedItem().toString());
            if (doctor.getNombre() != null) {
                txtPrecioConsulta.setText(String.valueOf(doctor.getPrecio()));
                txtConsultaEspecialidad.setText(doctor.getEspecialidad());

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_cboDoctorItemStateChanged

    private void btnBuscarPacienteConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteConsultaActionPerformed
        // TODO add your handling code here:
        try {
            BDPaciente bdpacien = new BDPaciente();
            Paciente paciente = bdpacien.buscarPaciente(txtConsultaPaciente.getText());
            if (paciente.getRut() != null) {
                txtnPacienteConsulta.setText(paciente.getNombre());
                txtaPacienteConsulta.setText(paciente.getApellido());

            } else {
                JOptionPane.showMessageDialog(null, "Paciente no encontrado, debe agregar nuevo paciente");
                limpiarControles();
                txtConsultaPaciente.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPacienteConsultaActionPerformed

    private void btnListarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarConsultaActionPerformed
        // TODO add your handling code here:
        try {
            int fila = 0;
            BDConsulta consulta = new BDConsulta();
            String [] titulos = {"IDCONSULTA", "FECHA", "RUT PACIENTE", "RUT DOCTOR", "PRECIO"};
            ArrayList<Consulta> lista = consulta.listarConsulta();
            for(Consulta consul:lista) {
                matriz[fila][0] = String.valueOf(consul.getIdConsulta());
                matriz[fila][1] = String.valueOf(consul.getFechaConsulta());
                matriz[fila][2] = consul.getRutPaciente();
                matriz[fila][3] = consul.getRutDoctor();
                matriz[fila][4] = String.valueOf(consul.getPrecioDoctor());
                fila++;
            }
            modelo = new DefaultTableModel(matriz,titulos);
            tblConsulta.setModel(modelo);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListarConsultaActionPerformed

    private void txtBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarConsultaActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txtBuscarConsultaActionPerformed

    private void btnBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConsultaActionPerformed
        // TODO add your handling code here:
        try {
            BDConsulta bdconsulta = new BDConsulta();
            Consulta consul = bdconsulta.buscarConsulta(txtBuscarConsulta.getText());
            if (consul.getRutPaciente()!= null) {
                txaConsulta.setText("");
                txaConsulta.append(consul.toString());
                limpiarControles();
                txtBuscarConsulta.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Paciente no tiene consulta");
                limpiarControles();
                txtBuscarConsulta.requestFocus();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarConsultaActionPerformed

    private void btnLimpiarTxtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTxtaActionPerformed
        // TODO add your handling code here:
        try {
            txaConsulta.setText("");
            limpiarControles();
            txtConsultaPaciente.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_btnLimpiarTxtaActionPerformed

    private void btnLimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiartablaActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
    }//GEN-LAST:event_btnLimpiartablaActionPerformed

    private void btnLimpiarTablaPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaPacActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarTablaPacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        BDAcceso bdacesso = new BDAcceso();
        try {        
            Acceso access = bdacesso.buscarUsuario(txtUsuario.getText(), txtClave.getText());
            boolean validar = bdacesso.validarAcceso(access.getUsuario(), access.getClave());
            if (validar) {
                jtPanel.setVisible(true);
            } else {
                lblMensaje.setVisible(true);
                lblMensaje.setText("Usuario o clave incorrecto");
                        
            }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Usuario o clave incorrecto");
        }
        
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConsultaActionPerformed
        // TODO add your handling code here:
        try {
            BDConsulta bdconsulta = new BDConsulta();
            if (bdconsulta.eliminarConsulta(txtConsultaPaciente.getText()) != 0) {
                JOptionPane.showMessageDialog(null, "Consulta eliminada");
                limpiarControles();
                txtConsultaPaciente.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró paciente con consulta para eliminar");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarConsultaActionPerformed

    private void tblConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMouseClicked
        // TODO add your handling code here:
        int fila = tblConsulta.getSelectedRow();
        txtConsultaPaciente.setText(tblConsulta.getValueAt(fila,2).toString());
 
    }//GEN-LAST:event_tblConsultaMouseClicked

    private void btnLimpiarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDoctorActionPerformed
        // TODO add your handling code here:
        limpiarControles();
    }//GEN-LAST:event_btnLimpiarDoctorActionPerformed

    private void btnLimpiarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPacienteActionPerformed
        // TODO add your handling code here:
        limpiarControles();
    }//GEN-LAST:event_btnLimpiarPacienteActionPerformed

    private void btnLimpiarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarConsultaActionPerformed
        // TODO add your handling code here:
        limpiarControles();
    }//GEN-LAST:event_btnLimpiarConsultaActionPerformed

    
    public void limpiarControles() {
        txtRutPaciente.setText("");
        txtNombrePaciente.setText("");
        txtApPaciente.setText("");
        txtCorreoPaciente.setText("");
        jdatePaciente.setDate(null);
        
        txtRutDoctor.setText("");
        txtNombreDoctor.setText("");
        txtApDoctor.setText("");
        txtCorreoDoctor.setText("");
        jdateDoctor.setDate(null);
        txtEspecialidad.setText("");
        txtPrecioDoctor.setText(null);
        
        txtConsultaPaciente.setText("");
        txtConsultaPaciente.setText("");
        txtnPacienteConsulta.setText("");
        txtaPacienteConsulta.setText("");
        cboDoctor.setSelectedIndex(0);
        txtConsultaEspecialidad.setText("");
        txtPrecioConsulta.setText("");
        jdateConsulta.setDate(null);
        
        txtBuscarConsulta.setText("");
               
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnBuscarConsulta;
    private javax.swing.JButton btnBuscarDoctor;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnBuscarPacienteConsulta;
    private javax.swing.JButton btnEliminarConsulta;
    private javax.swing.JButton btnEliminarDoctor;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnGuardarConsulta;
    private javax.swing.JButton btnGuardarPaciente;
    private javax.swing.JButton btnInsertarDoctor;
    private javax.swing.JButton btnLimpiarConsulta;
    private javax.swing.JButton btnLimpiarDoctor;
    private javax.swing.JButton btnLimpiarPaciente;
    private javax.swing.JButton btnLimpiarTablaPac;
    private javax.swing.JButton btnLimpiarTxta;
    private javax.swing.JButton btnLimpiartabla;
    private javax.swing.JButton btnListarConsulta;
    private javax.swing.JButton btnListarDoctor;
    private javax.swing.JButton btnListarPaciente;
    private javax.swing.JComboBox<String> cboDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jdateConsulta;
    private com.toedter.calendar.JDateChooser jdateDoctor;
    private com.toedter.calendar.JDateChooser jdatePaciente;
    private javax.swing.JPanel jpBuscarConsulta;
    private javax.swing.JPanel jpConsulta;
    private javax.swing.JPanel jpDoctor;
    private javax.swing.JPanel jpPaciente;
    private javax.swing.JPanel jpbienvenida;
    private javax.swing.JInternalFrame jplogin;
    private javax.swing.JTabbedPane jtPanel;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JTable tblPaciente;
    private javax.swing.JTextArea txaConsulta;
    private javax.swing.JTextField txtApDoctor;
    private javax.swing.JTextField txtApPaciente;
    private javax.swing.JTextField txtBuscarConsulta;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtConsultaEspecialidad;
    private javax.swing.JLabel txtConsultaNombreP;
    private javax.swing.JTextField txtConsultaPaciente;
    private javax.swing.JTextField txtCorreoDoctor;
    private javax.swing.JTextField txtCorreoPaciente;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtNombreDoctor;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtPrecioConsulta;
    private javax.swing.JTextField txtPrecioDoctor;
    private javax.swing.JTextField txtRutDoctor;
    private javax.swing.JTextField txtRutPaciente;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtaPacienteConsulta;
    private javax.swing.JTextField txtnPacienteConsulta;
    // End of variables declaration//GEN-END:variables
}
